on:
  release:
    types: [published]
    
env:
  GAME_TITLE: gameoff-2020
  ITCH_USER: Lounge Dev Knights
  PACKAGE_PREFIX: gameoff

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download Windows
        id: download-windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PACKAGE_PREFIX }}-windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: ${{ env.GAME_TITLE }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PACKAGE_PREFIX }}-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}
      
      - name: download Linux
        id: download-linux
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ${{ env.PACKAGE_PREFIX }}-linux.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GH_CREDENTIALS }}"
      - name: deploy to itch.io (Windows)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: linux
          ITCH_GAME: ${{ env.GAME_TITLE }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: ${{ env.PACKAGE_PREFIX }}-windows.zip
          VERSION: ${{ steps.download-windows.outputs.version }}

